version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meros_app
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html:cached
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    container_name: wordpress_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
